### ISSUE TITLE
Users should not need to test with Perl Critic

### ISSUE THREAD

**Issue by frioux** [hakamadare/webservice-pushover#8]
I have no problem with perl critic, but as a user, needing to install it and test it to verify that your module works is silly.  It would make a lot more sense for that to run as an author test and not for end users.  I can supply patches if you are interested.

**Comment by hakamadare** [comment]
sure, patches welcome!  ideally i'd like to see Test::Perl::Critic, Test::Pod::Coverage, and Test::Pod run as author-only tests.
